notifications:
  /autoware/localization/state:
    situations:
      - condition: Always
        code: LOC-001

  /autoware/planning/routing/state:
    situations:
      - condition: LocalizationState(Initialized)
        code: PLN-001-A

  /autoware/control:
    situations:
      - condition: RouteState(Set)
        code: CTL-001
