notifications:
  /autoware/localization/state:
    failures:
      - condition: Always
        code: LOC-001

  /autoware/planning/routing/state:
    failures:
      - condition: LocalizationState(Initialized)
        code: PLN-001

  /autoware/control:
    failures:
      - condition: RouteState(Set)
        code: CTL-001
