# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoware_protobuf/std_msgs/msg/header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autoware_protobuf.std_msgs.msg import time_pb2 as autoware__protobuf_dot_std__msgs_dot_msg_dot_time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='autoware_protobuf/std_msgs/msg/header.proto',
  package='std_msgs.msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+autoware_protobuf/std_msgs/msg/header.proto\x12\x0cstd_msgs.msg\x1a)autoware_protobuf/std_msgs/msg/time.proto\"=\n\x06Header\x12!\n\x05stamp\x18\x01 \x01(\x0b\x32\x12.std_msgs.msg.Time\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[autoware__protobuf_dot_std__msgs_dot_msg_dot_time__pb2.DESCRIPTOR,])




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='std_msgs.msg.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='std_msgs.msg.Header.stamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='std_msgs.msg.Header.frame_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=165,
)

_HEADER.fields_by_name['stamp'].message_type = autoware__protobuf_dot_std__msgs_dot_msg_dot_time__pb2._TIME
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'autoware_protobuf.std_msgs.msg.header_pb2'
  # @@protoc_insertion_point(class_scope:std_msgs.msg.Header)
  ))
_sym_db.RegisterMessage(Header)


# @@protoc_insertion_point(module_scope)
