# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoware_protobuf/std_msgs/msg/time.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autoware_protobuf/std_msgs/msg/time.proto',
  package='std_msgs.msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)autoware_protobuf/std_msgs/msg/time.proto\x12\x0cstd_msgs.msg\"$\n\x04Time\x12\x0b\n\x03sec\x18\x01 \x01(\x05\x12\x0f\n\x07nanosec\x18\x02 \x01(\rb\x06proto3')
)




_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='std_msgs.msg.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='std_msgs.msg.Time.sec', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nanosec', full_name='std_msgs.msg.Time.nanosec', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Time'] = _TIME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), dict(
  DESCRIPTOR = _TIME,
  __module__ = 'autoware_protobuf.std_msgs.msg.time_pb2'
  # @@protoc_insertion_point(class_scope:std_msgs.msg.Time)
  ))
_sym_db.RegisterMessage(Time)


# @@protoc_insertion_point(module_scope)
