# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoware_protobuf/std_msgs/msg/uint32.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autoware_protobuf/std_msgs/msg/uint32.proto',
  package='std_msgs.msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+autoware_protobuf/std_msgs/msg/uint32.proto\x12\x0cstd_msgs.msg\"\x16\n\x06UInt32\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\rb\x06proto3')
)




_UINT32 = _descriptor.Descriptor(
  name='UInt32',
  full_name='std_msgs.msg.UInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='std_msgs.msg.UInt32.data', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['UInt32'] = _UINT32
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UInt32 = _reflection.GeneratedProtocolMessageType('UInt32', (_message.Message,), dict(
  DESCRIPTOR = _UINT32,
  __module__ = 'autoware_protobuf.std_msgs.msg.uint32_pb2'
  # @@protoc_insertion_point(class_scope:std_msgs.msg.UInt32)
  ))
_sym_db.RegisterMessage(UInt32)


# @@protoc_insertion_point(module_scope)
