/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.std_msgs.msg.Header');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.std_msgs.msg.Time');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.std_msgs.msg.Header = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.std_msgs.msg.Header, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.std_msgs.msg.Header.displayName = 'proto.std_msgs.msg.Header';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.std_msgs.msg.Header.prototype.toObject = function(opt_includeInstance) {
  return proto.std_msgs.msg.Header.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.std_msgs.msg.Header} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.std_msgs.msg.Header.toObject = function(includeInstance, msg) {
  var f, obj = {
    stamp: (f = msg.getStamp()) && proto.std_msgs.msg.Time.toObject(includeInstance, f),
    frameId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.std_msgs.msg.Header}
 */
proto.std_msgs.msg.Header.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.std_msgs.msg.Header;
  return proto.std_msgs.msg.Header.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.std_msgs.msg.Header} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.std_msgs.msg.Header}
 */
proto.std_msgs.msg.Header.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.std_msgs.msg.Time;
      reader.readMessage(value,proto.std_msgs.msg.Time.deserializeBinaryFromReader);
      msg.setStamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrameId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.std_msgs.msg.Header.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.std_msgs.msg.Header.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.std_msgs.msg.Header} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.std_msgs.msg.Header.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStamp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.std_msgs.msg.Time.serializeBinaryToWriter
    );
  }
  f = message.getFrameId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional Time stamp = 1;
 * @return {?proto.std_msgs.msg.Time}
 */
proto.std_msgs.msg.Header.prototype.getStamp = function() {
  return /** @type{?proto.std_msgs.msg.Time} */ (
    jspb.Message.getWrapperField(this, proto.std_msgs.msg.Time, 1));
};


/** @param {?proto.std_msgs.msg.Time|undefined} value */
proto.std_msgs.msg.Header.prototype.setStamp = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.std_msgs.msg.Header.prototype.clearStamp = function() {
  this.setStamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.std_msgs.msg.Header.prototype.hasStamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string frame_id = 2;
 * @return {string}
 */
proto.std_msgs.msg.Header.prototype.getFrameId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.std_msgs.msg.Header.prototype.setFrameId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


