/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.geometry_msgs.msg.PoseStamped');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.geometry_msgs.msg.Pose');
goog.require('proto.std_msgs.msg.Header');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.geometry_msgs.msg.PoseStamped = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.geometry_msgs.msg.PoseStamped, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.geometry_msgs.msg.PoseStamped.displayName = 'proto.geometry_msgs.msg.PoseStamped';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.geometry_msgs.msg.PoseStamped.prototype.toObject = function(opt_includeInstance) {
  return proto.geometry_msgs.msg.PoseStamped.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.geometry_msgs.msg.PoseStamped} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.geometry_msgs.msg.PoseStamped.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && proto.std_msgs.msg.Header.toObject(includeInstance, f),
    pose: (f = msg.getPose()) && proto.geometry_msgs.msg.Pose.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.geometry_msgs.msg.PoseStamped}
 */
proto.geometry_msgs.msg.PoseStamped.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.geometry_msgs.msg.PoseStamped;
  return proto.geometry_msgs.msg.PoseStamped.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.geometry_msgs.msg.PoseStamped} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.geometry_msgs.msg.PoseStamped}
 */
proto.geometry_msgs.msg.PoseStamped.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.std_msgs.msg.Header;
      reader.readMessage(value,proto.std_msgs.msg.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.geometry_msgs.msg.Pose;
      reader.readMessage(value,proto.geometry_msgs.msg.Pose.deserializeBinaryFromReader);
      msg.setPose(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.geometry_msgs.msg.PoseStamped.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.geometry_msgs.msg.PoseStamped.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.geometry_msgs.msg.PoseStamped} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.geometry_msgs.msg.PoseStamped.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.std_msgs.msg.Header.serializeBinaryToWriter
    );
  }
  f = message.getPose();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.geometry_msgs.msg.Pose.serializeBinaryToWriter
    );
  }
};


/**
 * optional std_msgs.msg.Header header = 1;
 * @return {?proto.std_msgs.msg.Header}
 */
proto.geometry_msgs.msg.PoseStamped.prototype.getHeader = function() {
  return /** @type{?proto.std_msgs.msg.Header} */ (
    jspb.Message.getWrapperField(this, proto.std_msgs.msg.Header, 1));
};


/** @param {?proto.std_msgs.msg.Header|undefined} value */
proto.geometry_msgs.msg.PoseStamped.prototype.setHeader = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.geometry_msgs.msg.PoseStamped.prototype.clearHeader = function() {
  this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.geometry_msgs.msg.PoseStamped.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Pose pose = 2;
 * @return {?proto.geometry_msgs.msg.Pose}
 */
proto.geometry_msgs.msg.PoseStamped.prototype.getPose = function() {
  return /** @type{?proto.geometry_msgs.msg.Pose} */ (
    jspb.Message.getWrapperField(this, proto.geometry_msgs.msg.Pose, 2));
};


/** @param {?proto.geometry_msgs.msg.Pose|undefined} value */
proto.geometry_msgs.msg.PoseStamped.prototype.setPose = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.geometry_msgs.msg.PoseStamped.prototype.clearPose = function() {
  this.setPose(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.geometry_msgs.msg.PoseStamped.prototype.hasPose = function() {
  return jspb.Message.getField(this, 2) != null;
};


