/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.std_msgs.msg.Time');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.std_msgs.msg.Time = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.std_msgs.msg.Time, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.std_msgs.msg.Time.displayName = 'proto.std_msgs.msg.Time';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.std_msgs.msg.Time.prototype.toObject = function(opt_includeInstance) {
  return proto.std_msgs.msg.Time.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.std_msgs.msg.Time} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.std_msgs.msg.Time.toObject = function(includeInstance, msg) {
  var f, obj = {
    sec: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nanosec: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.std_msgs.msg.Time}
 */
proto.std_msgs.msg.Time.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.std_msgs.msg.Time;
  return proto.std_msgs.msg.Time.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.std_msgs.msg.Time} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.std_msgs.msg.Time}
 */
proto.std_msgs.msg.Time.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSec(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNanosec(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.std_msgs.msg.Time.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.std_msgs.msg.Time.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.std_msgs.msg.Time} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.std_msgs.msg.Time.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSec();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNanosec();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional int32 sec = 1;
 * @return {number}
 */
proto.std_msgs.msg.Time.prototype.getSec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.std_msgs.msg.Time.prototype.setSec = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 nanosec = 2;
 * @return {number}
 */
proto.std_msgs.msg.Time.prototype.getNanosec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.std_msgs.msg.Time.prototype.setNanosec = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


